package com.example.demo.Enums;

public enum Widget {

    ORDER_MINI_STATS,
    ORDER_BY_STATUS,
    ORDER_VALUE_OVER_TIME,
    ORDER_TOP_CUSTOMERS,
    ORDER_RECENT_ORDERS,

    PRODUCT_MINI_STATS,
    PRODUCT_TOP_SELLING_PRODUCTS,
    PRODUCT_BY_CATEGORY,
    PRODUCT_LOW_STOCK,
    PRODUCT_PERFORMANCE,

    MATERIAL_MINI_STATS,
    MATERIAL_BY_STATUS,
    MATERIAL_USAGE_OVERTIME,
    MATERIAL_LOW_STOCK,
    MATERIAL_RECENT_MOVEMENT

}
